
homeassistant:
  # Name of the location where Home Assistant is running
  name: Andersens
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob:
    "group.*lights":
      custom_ui_state_card: state-card-custom-ui
      icon: mdi:lightbulb
      templates:
        icon: "if (state === 'on') return 'mdi:lightbulb'; else return 'mdi:power-standby';"
        icon_color: "if (state === 'on') return 'rgb(239, 239, 0)'; else return 'rgb(3, 169, 244)';"
zone:
  - name: School
    latitude: !secret school-latitude
    longitude: !secret school-longitude
    radius: 50
    icon: mdi:school

  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50
    icon: mdi:home

# Enables the frontend
frontend:

panel_iframe:
  terminal:
    title: Terminal
    icon: mdi:console
    url: https://hassio.local:7681
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://hassio.local:8321


# Example using a delay after start of Home Assistant
homekit:
  auto_start: True
  filter: &cloudfilters
    exclude_domains:
      - script
      - automation
    exclude_entities:
      - switch.fluxer
      - light.hallway_light_3
      - light.hallway_light_5
      - light.hallway_light_2
      - light.hallway_light_1
      - light.hallway_light_4
      - light.kitchen_light_2
      - light.kitchen_table_light_2
      - light.kitchen_light_4
      - light.kitchen_light_5
      - light.kitchen_table_light_1
      - light.kitchen_light_1
      - light.kitchen_light_6
      - light.kitchen_cupboard_light_2
      - light.kitchen_cupboard_light_1
      - light.kitchen_light_3
      - light.winter_garden_light_1
      - light.winter_garden_light_2
      - light.winter_garden_light_4
      - light.winter_garden_light_3
      - light.winter_garden_light_5
      - light.basement_light_4
      - light.basement_light_1
      - light.basement_light_stairs
      - light.basement_light_3
      - light.basement_light_9
      - light.basement_light_10
      - light.basement_light_8
      - light.basement_light_2
      - light.basement_light_7
      - light.basement_light_6
      - light.basement_light_5

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.107
    token: !secret rockrobo-token

media_player:
  - platform: ps4
    host: 192.168.1.160

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http-base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: intermediate
  trusted_networks:
    - 192.168.1.42
    - 192.168.1.113

ios:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

system_health:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# enable video playback
ffmpeg:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#prometheus:
#  namespace: hass

# Weather prediction
sensor:
  - platform: uptime
    name: uptime
    unit_of_measurement: hours
  - platform: yr
  - platform: ring
  - platform: aftership
    name: account1
    api_key: !secret aftership-api_key
  - platform: aftership
    name: account2
    api_key: !secret aftership-api_key
  - platform: seventeentrack
    username: !secret seventeentrack-username
    password: !secret seventeentrack-password
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_1m
      - type: processor_use
      - type: last_boot
      - type: network_in
      - type: network_out

switch:
  - platform: flux
    name: fluxer
    mode: mired
    lights:
      - group.kitchen_lights
      - group.dinner_table_lights
      - group.hallway_lights
      - group.kitchen_table_lights
      - light.dinner_table_wall_light
  - platform: broadlink
    host: !secret broadlink-host
    mac: !secret broadlink-mac
    timeout: 15
    switches:
      humidifier:
        friendly_name: "Bedroom humidifer on"
        command_on: 'JgBQAAABLJQUEREVExIUEREVEzcRFRMRFDcUNxA6FDcTNxEVEzcRORQSETkUEhEUFBEUEhEUFBEUNxMSFDcTNxE6FDcTNxE4FQAFKgABLEkTAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABLJQUEREVExIUEREVEzcRFRMRFDcUNxA6FDcTNxEVEzcRORQSETkUEhEUFBEUEhEUFBEUNxMSFDcTNxE6FDcTNxE4FQAFKgABLEkTAA0FAAAAAAAAAAA='
      humidifier_down:
        friendly_name: "Bedroom humidifier down"
        command_on: 'JgBYAAABKpUUERMTERQTEhQSEDoUEhAVEzcROhM4EzcRORQSETkUNxQ3EBUTEhQREToUEREVExIUERE5FDcUNxEUFDcRORQ3EwAFKwABK0oUAAxyAAEsSRQADQU='
        command_off: 'JgBYAAABKpUUERMTERQTEhQSEDoUEhAVEzcROhM4EzcRORQSETkUNxQ3EBUTEhQREToUEREVExIUERE5FDcUNxEUFDcRORQ3EwAFKwABK0oUAAxyAAEsSRQADQU='
      humidifier_up:
        friendly_name: "Bedroom humidifier up"
        command_on: 'JgBYAAABK5QUERQSERQTEhQSETkUEREVEzcROhM4EjgRORQSETkUNxMSFDcTEhM4ExITEhEVEhMTOBISEzkRExQ3EToRORM4EwAFKwABK0oTAAx0AAEpSxQADQU='
        command_off: 'JgBYAAABK5QUERQSERQTEhQSETkUEREVEzcROhM4EjgRORQSETkUNxMSFDcTEhM4ExITEhEVEhMTOBISEzkRExQ3EToRORM4EwAFKwABK0oTAAx0AAEpSxQADQU='
      humidifier_speed:
        friendly_name: "Bedroom humidifier Speed"
        command_on:  'JgBYAAABKZcSExITERURExMTETkSFBEUEjkRORI5EjgROhEUEjkROhETEzgSExM4EjkRFBIUERMSORITEjkRFBIUEjgRORM4EQAFLgABKUsSAAx1AAEoTBMADQU='
        command_off: 'JgBYAAABKZcSExITERURExMTETkSFBEUEjkRORI5EjgROhEUEjkROhETEzgSExM4EjkRFBIUERMSORITEjkRFBIUEjgRORM4EQAFLgABKUsSAAx1AAEoTBMADQU='
      humidifier_timer:
        friendly_name: "Bedroom humidifier Timer"
        command_on:  'JgBYAAABKZYSFBITERQRFREUETkTEhEVETkROhI5ETkRORMTEjgSORE6EBURFRI4EjgRFRITEhMRFRE5ETkSFBEVETkRORM4EgAFLAABKksSAAx0AAEpTBIADQU='
        command_off: 'JgBYAAABKZYSFBITERQRFREUETkTEhEVETkROhI5ETkRORMTEjgSORE6EBURFRI4EjgRFRITEhMRFRE5ETkSFBEVETkRORM4EgAFLAABKksSAAx0AAEpTBIADQU='
      humidifier_mode:
        friendly_name: "Bedroom humidifier Mode"
        command_on:  'JgBYAAABK5QUERQSEhMTEhQREzgUERMTEzcTNxU2FDcTNxQSEjgUNxM3ExMTEhQ3ExIUERMTExEUEhM3FDcUERQ3FDYTOBQ3EwAFKwABK0kVAAxyAAErShQADQU='
        command_off: 'JgBYAAABK5QUERQSEhMTEhQREzgUERMTEzcTNxU2FDcTNxQSEjgUNxM3ExMTEhQ3ExIUERMTExEUEhM3FDcUERQ3FDYTOBQ3EwAFKwABK0kVAAxyAAErShQADQU='
      sony_tv:
        friendly_name: "Bedroom TV"
        command_on: 'JgCMAFESKRIWEikSFhIpEhYSFRIqEhUSFhIVExUAA1FREikTFRIpExUSKRMVEhYSKRIWEhUTFRIWAANRURIpEhYSKRIWEikSFhIVEioSFRMVEhUTFQADU1ESKRIWEikSFhIpEhYSFRMpEhUTFRIVExUAA1NREikSFhIpEhYSKRIWEhUSKhIVEhYSFRMVAA0FAAAAAAAAAAAAAAAA'
        command_off: 'JgCMAFESKRIWEikSFhIpEhYSFRIqEhUSFhIVExUAA1FREikTFRIpExUSKRMVEhYSKRIWEhUTFRIWAANRURIpEhYSKRIWEikSFhIVEioSFRMVEhUTFQADU1ESKRIWEikSFhIpEhYSFRMpEhUTFRIVExUAA1NREikSFhIpEhYSKRIWEhUSKhIVEhYSFRMVAA0FAAAAAAAAAAAAAAAA'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
  alexa:
    filter:
      <<: *cloudfilters

device_tracker:
  - platform: swisscom
    new_device_defaults:
      track_new_devices: false
  - platform: bluetooth_tracker

ring:
   username: !secret ring-username
   password: !secret ring-password

input_boolean:
  test_motion:
    name: Flag to test
    initial: off
    icon: mdi:motion

binary_sensor:
   - platform: ring
   - platform: template
     sensors:
      presence_basement_combined:
        friendly_name: "Basement Motion Anywhere"
        value_template: >-
          {{ is_state('binary_sensor.presence_basement', 'on')
          or is_state('binary_sensor.presence_basement_stairs', 'on') }}


lock:
  - platform: nuki
    host: 192.168.1.133
    token: !secret nuki-token

camera:
  - platform: ring
  - platform: mjpeg
    name: babymonitor
    mjpeg_url: !secret baby-mjpeg_url
    still_image_url: !secret baby-still_image_url
#  - platform: synology
#    url: !secret synology_url
#    username: !secret synology_username 
#    password: !secret synology_password
#    verify_ssl: false


  # logger:
  #   default: info
  #   logs:
  #     pydeconz: debug
  #     homeassistant.components.deconz: debug


lovelace:
  mode: yaml

recorder:
  db_url: !secret db_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
