homeassistant:
  # Name of the location where Home Assistant is running
  name: Andersens
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml

zone:
  - name: School
    latitude: !secret school-latitude
    longitude: !secret school-longitude
    radius: 50
    icon: mdi:school

  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50
    icon: mdi:home

# Enables the frontend
frontend:

# Example using a delay after start of Home Assistant
homekit:
  auto_start: True

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.118
    token: !secret rockrobo-token

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http-base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: intermediate
  trusted_networks: 
    - 192.168.1.42
    - 192.168.1.113

ios:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# enable video playback
ffmpeg:

# View all events in a logbook
logbook:
 
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

prometheus:
  namespace: hass

# Weather prediction
sensor:
  - platform: yr
  - platform: ring
  - platform: aftership
    api_key: !secret aftership-api_key


# Text to speech
tts:
  - platform: google

# Cloud
cloud:

device_tracker:
  - platform: swisscom
    new_device_defaults:
      track_new_devices: false
  - platform: bluetooth_tracker

ring:
   username: !secret ring-username
   password: !secret ring-password

input_boolean:
  test_motion:
    name: Flag to test
    initial: off
    icon: mdi:motion

binary_sensor:
   - platform: ring
   - platform: template
     sensors:
      presence_basement_combined:
        friendly_name: "Basement Motion Anywhere"
        value_template: >-
          {{ is_state('binary_sensor.presence_basement', 'on')
          or is_state('binary_sensor.presence_basement_stairs', 'on') }}


#lock:
#  - platform: nuki
#    host: 192.168.1.115
#    token: !secret nuki-token

camera:
   - platform: ring
   - platform: mjpeg
     name: babymonitor
     mjpeg_url: !secret baby-mjpeg_url
     still_image_url: !secret baby-still_image_url

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'

  # logger:
  #   default: info
  #   logs:
  #     pydeconz: debug
  #     homeassistant.components.deconz: debug

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
