
## WARNING: This is a generated file
## will eventually be overwritten


automation:
  - alias: Turn on dinner table when there is movement
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_dinner_table
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.timer_dinner_table
      - service: homeassistant.turn_on
        entity_id: group.dinner_table_lights
  - alias: Turn off dinner table lights at end of timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_dinner_table
    action:
      - service: homeassistant.turn_off
        entity_id: group.dinner_table_lights

timer:
      timer_dinner_table:
          duration: "00:15:00"

group:  
  dinner_table_motionview:
    name: dinner table
    entities:
      - binary_sensor.presence_dinner_table
      - timer.timer_dinner_table
      - group.dinner_table_lights
