
## WARNING: This is a generated file
## will eventually be overwritten


automation:
  - alias: Turn on hallway when there is movement
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_hallway
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.timer_hallway
      - service: homeassistant.turn_on
        entity_id: group.hallway_lights
  - alias: Turn off hallway lights at end of timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_hallway
    action:
      - service: homeassistant.turn_off
        entity_id: group.hallway_lights

timer:
      timer_hallway:
          duration: "00:15:00"

group:  
  hallway_motionview:
    name: hallway
    entities:
      - binary_sensor.presence_hallway
      - timer.timer_hallway
      - group.hallway_lights
